### ISSUE TITLE
util/ssl_scan_sock.py timeouts on certain domains

### ISSUE THREAD

**Issue by gjedeer** [danwent/Perspectives-Server#61]
The first _read_record() in _run_scan() times out for certain domains. One example is git.cocaine.ninja:443.

I tried debugging it but long hex strings without explanation are beyond my level of hardcore.

Alternatively, is there a way to switch to the OpenSSL scanner without changing code?

**Comment by gjedeer** [comment]
Okay, I see it's fixed in https://github.com/danwent/Perspectives-Server/pull/55/files

**Comment by daveschaefer** [comment]
Hey @gjedeer - yes, you shouldn't have to hack the hardcoded hex strings ;)

I have a patch in progress for this, as part of the overall work on the scanner. This is third on my list, after pushing the AMO blocker and fixing the notary responses (see [the roadmap](https://github.com/danwent/Perspectives/wiki/Perspectives-Roadmap)).

Thanks for the report!

**Comment by gjedeer** [comment]
Thank you for your answer. In the meanwhile, I have patched my personal notary to work with openssl scanner, so i will be able to do some QA for openssl before it's used as default.

On June 9, 2016 6:29:36 AM CEST, Dave <notifications@github.com> wrote:
>Hey @gjedeer - yes, you shouldn't have to hack the hardcoded hex
>strings ;)
>
>I have a patch in progress for this, as part of the overall work on the
>scanner. This is third on my list, after pushing the AMO blocker and
>fixing the notary responses (see [the
>roadmap](https://github.com/danwent/Perspectives/wiki/Perspectives-Roadmap)).
>
>Thanks for the report!
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/danwent/Perspectives-Server/issues/61#issuecomment-224797445

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
